export const LOAD_TRACKINGS = 'LOAD_TRACKINGS';
export const ADD_TRACKING = 'ADD_TRACKING';
export const REMOVE_TRACKING = 'REMOVE_TRACKING';
export const PACKAGE_STATUS = 'PACKAGE_STATUS';
export const UPDATE_TRACKING = 'UPDATE_TRACKING';
export const UPDATE_CARRIER = 'UPDATE_CARRIER';
export const UPDATE_LABEL = 'UPDATE_LABEL';
